# Configuration file for the NEMO Fetch tool - an automatic downloader of files.
# (In YAML format https://en.wikipedia.org/wiki/YAML )

# An explanation of most of these options is available in the file README.md
#  -> Viewable here: http://rhe-neo-dev-repo.dev.lan/git/blob/pma!fetch.git/master/README.md

# The work directory (for log and lock files):
directory: /home/547/smr547/data/fetch

# Notification settings (for errors):
notify:
  email: ['steven.ring@ga.gov.au']

# Logging level for modules (any python module can be added here)
log:
  fetch: DEBUG
  neocommon: DEBUG
  neocommon.files: INFO

# Download rules:
rules:

  Invariant GEO Potential:
    schedule: '0 16 25 * *'
    source: !ecmwf-api
        target_dir: /home/547/smr547/ecmwf_data
        settings:  
                class: "ei"
                dataset: "interim"
                date: "1989-01-01"
                expver: "1"
                grid: "0.125/0.125"
                levtype: "sfc"
                param: "129.128"
                step: "0"
                stream: "oper"
                time: "12:00:00"
                type: "an"
                target: /home/547/smr547/ecmwf_data/invar_geo_potential.grib


