# Configuration file for the NEMO Fetch tool - an automatic downloader of files.
# (In YAML format https://en.wikipedia.org/wiki/YAML )

# An explanation of most of these options is available in the file README.md
#  -> Viewable here: http://rhe-neo-dev-repo.dev.lan/git/blob/pma!fetch.git/master/README.md

# The work directory (for log and lock files):
directory: /home/547/smr547/data/fetch

# Notification settings (for errors):
# notify:
#  email: ['steven.ring@ga.gov.au']

# Logging level for modules (any python module can be added here)
log:
  fetch: DEBUG
  neocommon: DEBUG
  neocommon.files: INFO

# Download rules:
rules:
  Invariant GEO Potential:
    schedule: '0 16 25 * *'
    source: !ecmwf-api
        target_dir: /home/547/smr547/ecmwf_data
        settings:  
                class: "ei"
                dataset: "interim"
                date: "1989-01-01"
                expver: "1"
                grid: "0.125/0.125"
                levtype: "sfc"
                param: "129.128"
                step: "0"
                stream: "oper"
                time: "12:00:00"
                type: "an"
                target: /home/547/smr547/ecmwf_data/invar_geo_potential.grib

  Surface Pressure:
    schedule: '0 16 26 * *'
    source: !ecmwf-api
        target_dir: /home/547/smr547/ecmwf_data
        settings:  
                class: "ei"
                dataset: "interim"
                date: "2005-01-03/to/2005-01-05"
                area: "0/100/-50/160"
                expver: "1"
                grid: "0.125/0.125"
                levtype: "sfc"
                param: "134.128"
                stream: "oper"
                time: "00:00:00"
                step: "0"
                type: "an"
                target: /home/547/smr547/ecmwf_data/sp_20050103_to_20050105.grib



  Temperature:
    schedule: '0 17 26 * *'
    source: !ecmwf-api
        target_dir: /home/547/smr547/ecmwf_data
        settings:              
                class: "ei"
                dataset: "interim"
                date: "2002-05-05/to/2002-05-05"
                area: "0/100/-50/160"
                expver: "1"
                grid: "0.125/0.125"
                levtype: "sfc"
                param: "130.128"
                stream: "oper"
                time: "10:00:00"
                step: "0"
                type: "an"
                target: /home/547/smr547/ecmwf_data/temperature_20020505.grib
