[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0"]

[project]
dependencies = [
    # TODO move to optional
    "boto3>=1.42.25",
    "click>=8.2.1",
    "httpx>=0.28.1",
    "lxml>=5.4.0",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "pydantic>=2.11.5",
    "pyyaml>=6.0.2",
    "structlog>=25.3.0",
    "urllib3>=2.4.0"
]
description = "Find and download missing BRDF"
name = "fetch2"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[project.optional-dependencies]
test = ["pytest>=8.0.0", "pytest-mock>=3.14.0", "flask>=3.0.0"]

[project.scripts]
fetch2-brdf = "fetch2.brdf:cli"

[tool.basedpyright]
# This is less strict than pyright's recommended
typeCheckingMode = "strict"

[tool.pytest.ini_options]
addopts = "--doctest-modules"
python_classes = ["Test*"]
python_files = ["test_*.py", "*_test.py"]
python_functions = ["test_*"]
testpaths = ["tests", "src"]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

# deprecateTypingAliases = false
# reportAny = "deprecated"
# reportUnknownParameterType
